name: hotel_app
description: "A new Flutter project."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  #riverpod
  flutter_riverpod: ^2.6.1
  riverpod_annotation: ^2.6.1
  #dio
  dio: ^5.8.0+1
  logger: ^2.5.0
  #
  flutter_svg: ^2.1.0
  isar: ^3.1.0+1
  get_it: ^8.0.3
  dartz: ^0.10.1
  go_router: ^14.8.1
  shimmer: ^3.0.0
  cached_network_image: ^3.4.1
  shared_preferences: ^2.5.2
  path_provider: ^2.1.5
  fl_chart: ^0.63.0
  image_picker: ^1.1.2
  dotted_border: ^2.0.0
  syncfusion_flutter_pdfviewer: ^29.1.35
  flutter_map: ^8.1.1
  latlong2: ^0.9.1
  firebase_core: ^3.13.0
  firebase_messaging: ^15.2.5
  firebase_crashlytics: ^4.3.5
  flutter_local_notifications: ^19.2.0
  flutter_downloader: ^1.10.5
  url_launcher: ^6.1.14
  http: ^1.3.0
  intl: ^0.18.1
  qr_flutter: ^4.0.0
  excel: ^2.0.8
  permission_handler: ^12.0.0+1
  share_plus: ^11.0.0
  open_filex: ^4.7.0


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  build_runner: ^2.4.6

flutter:

  uses-material-design: true

  assets:
    - assets/images/
    - assets/icons/
    - assets/fonts/

